all: ReverseWordsCpp ReverseWordsJava ReverseWordsGo

ReverseWordsCpp:
	g++ -Wall -g -std=c++11 ReverseWords.cpp -o ReverseWordsCpp

ReverseWordsJava:
	javac ReverseWords.java

ReverseWordsGo:
	go build -o reverse_words_go reverse_words.go
