all: ReverseBinaryTreeCpp ReverseBinaryTreeJava ReverseBinaryTreeGo

ReverseBinaryTreeCpp:
	g++ -Wall -g -std=c++11 ReverseBinaryTree.cpp -o ReverseBinaryTreeCpp

ReverseBinaryTreeJava:
	javac ReverseBinaryTree.java

ReverseBinaryTreeGo:
	go build -o reverse_binary_tree_go reverse_binary_tree.go
